---
title: "Contributions done by African-American over time - tidytuesday 09/06/2020"
author: "Lucy Njoki"
date: "6/20/2020"
output: html_document
---

```{r setup, include=FALSE}

rm(list = ls())
knitr::opts_chunk$set(echo = TRUE,
                      warning  = FALSE,
                      message = FALSE,
                      fig.height = 0.6,
                      fig.width = 0.6)
```

```{r Package load}
library(tidyverse)
library(extrafont)
library(fcuk)
library(ggthemes)
```

## Load data

```{r load data}
firsts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-09/firsts.csv')


head(firsts)

```

##Exploring the firsts data
```{r Exploring data}
#str of the data
glimpse(firsts)

#checking for missing data
sapply(firsts, function(x) sum(is.na(x)))

#converting necessary vars into factors
firsts$category <- as.factor(firsts$category)
```

##Visualizing:
>__Distribution of achievements__

>__Distribution of achievement over time__
               
```{r}
firsts%>%
  count(category, sort  = TRUE) %>%
  mutate(category = fct_reorder(category, n)) %>%
  ggplot(aes(x = n, y = category)) +
  geom_bar(stat = "identity", width = 0.6, fill = "dark green") +
  geom_text(aes(label = paste(n, sep = "")), size = 4,
                hjust = -0.1, vjust = -0.25, 
                position = position_dodge(0.5)) +
  labs(caption = "plot:@lucy_njokinjuki",
       title = "Distribution of achivements of African-Americans",
       x = "Count", y = "Category") +
  theme(axis.line = element_line(size = 0.5, colour = "black"),
        plot.title = element_text(family = "Calibri",
                     size = rel(1.2), face = "bold",
                     hjust = 0.5),
         plot.subtitle = element_text(family = "Calibri", 
                        size = rel(1.2), hjust = 0.5),
         axis.title.x = element_text(family = "Calibri", 
                                      size = rel(1.0), hjust = 0.5),
          axis.title.y = element_text(family = "Calibri", 
                                       size = rel(1.0),
                                      hjust = 0.5)) 

ggplot(firsts, aes(x = year, fill = category)) +
  geom_histogram(bins = 30) +
  labs(caption = "plot:@lucy_njokinjuki",
           title = "Distribution of achivements of African-Americans over time",
           x = "Year", y = "Count") +
  theme(axis.line = element_line(size = 0.5, colour = "black"),
            plot.title = element_text(family = "Calibri",
                                               size = rel(1.2), face = "bold",
                                               hjust = 0.5),
            plot.subtitle = element_text(family = "Calibri", 
                                                  size = rel(1.2), hjust = 0.5),
            axis.title.x = element_text(family = "Calibri", 
                                                  size = rel(1.0), hjust = 0.5),
          axis.title.y = element_text(family = "Calibri", 
                                      size = rel(1.0),
                                      hjust = 0.5)) 
```