---
title: "BlackSlavery (Census) - 16/09/2020"
author: "Lucy Njoki"
date: "6/21/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE,
                      warning  = FALSE,
                      message = FALSE,
                      fig.height = 0.6,
                      fig.width = 0.6)
```

#Packages load

```{r package load}
library(tidyverse)
library(extrafont)
library(fcuk)
library(ggthemes)
library(patchwork)
```


## Load data

```{r load data}
census <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/census.csv')

head(census)
names(census)
```

## Exploring data
```{r exploring data}
#str of the data
glimpse(census)

#checking for missing data
sapply(census, function(x) sum(is.na(x)))
```

##Visualizing plots

```{r #Visualizing data}

Cens_black <- census %>%
  group_by(year) %>%
  summarise(Meanval1 = round(mean(black_free),0),
            Meanval2 = round(mean(black_slaves),0))

p1 <- ggplot(Cens_black, aes(x = year)) +
  geom_bar(stat = "identity", aes(y = Meanval1), fill = "darkblue") +
  geom_text(aes(y = Meanval1, label = paste(Meanval1, sep = "")), size = 4,
            hjust = 0.5, vjust = -0.25, 
            position = position_dodge(0.5))+
labs(caption = "plot:@lucy_njokinjuki",
       title = "Average number of free black population, 1790 - 1870",
       x = "Year", y = "Average") +
  theme(axis.line = element_line(size = 0.5, colour = "black"),
        plot.title = element_text(family = "Calibri",
                                  size = rel(1.2), face = "bold",
                                  hjust = 0.5),
        plot.subtitle = element_text(family = "Calibri", 
                                     size = rel(1.2), hjust = 0.5),
        axis.title.x = element_text(family = "Calibri", 
                                    size = rel(1.0), hjust = 0.5),
        axis.title.y = element_text(family = "Calibri", 
                                    size = rel(1.0),
                                    hjust = 0.5)) 
p2 <- ggplot(Cens_black, aes(x = year)) +
  geom_bar(stat = "identity", aes(y = Meanval2), fill = "darkred") +
  geom_text(aes(y = Meanval2, label = paste(Meanval2, sep = "")), size = 4,
            hjust = 0.5, vjust = -0.25, 
            position = position_dodge(0.5))+
  labs(caption = "plot:@lucy_njokinjuki",
       title = "Average number of enslaved black population, 1790 - 1870",
       x = "Year", y = "Average") +
  theme(axis.line = element_line(size = 0.5, colour = "black"),
        plot.title = element_text(family = "Calibri",
                                  size = rel(1.2), face = "bold",
                                  hjust = 0.5),
        plot.subtitle = element_text(family = "Calibri", 
                                     size = rel(1.2), hjust = 0.5),
        axis.title.x = element_text(family = "Calibri", 
                                    size = rel(1.0), hjust = 0.5),
        axis.title.y = element_text(family = "Calibri", 
                                    size = rel(1.0),
                                    hjust = 0.5)) 
options(scipen=999) #preventing scientific numbers from popping up in my plot:)

p1+p2
```

